name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ankane/setup-postgres@v1
        with:
          database: pgvector_fortran_test
          dev-files: true
      - run: |
          cd /tmp
          git clone --branch v0.8.0 https://github.com/pgvector/pgvector.git
          cd pgvector
          make
          sudo make install
      - uses: fortran-lang/setup-fpm@v5
        with:
          fpm-version: v0.10.1
      - run: fpm run
        env:
          FPM_CFLAGS: -I/usr/include/postgresql
